version: "3.8"
services:
  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=root
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: "listen --api-key sk_test_51NhOiqFwiLeydcwjFiac5xebXeAJlL1ygtESPrNpTKU6TuyCHpdl34n4iOp3u99Guofm9JB2EEaZHL9qeVQ2UXaf00aB8IWj6f --forward-to host.docker.internal:8080/webhook"
  backend:
    container_name: backend
    depends_on:
      - mysqldb
    build: ./swp-be
    restart: unless-stopped
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
  frontend:
    container_name: frontend
    build: ./swe-ui
    restart: unless-stopped
    ports:
      - 5173:5173
    stdin_open: true
    tty: true

volumes:
  db:
